# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha

    working_directory: ~/repo

    branches:
        only:
          - master # list of branches to build
          - release\/.+ # or regexes

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
#      KEYSTORE: ${CIRCLE_WORKING_DIRECTORY}/sigining.keystore
#      PUBLISHER_ACCT_JSON_FILE: ${CIRCLE_WORKING_DIRECTORY}/publisher_profile.json

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # build release
      - run: ./gradlew assembleRelease

      - store_artifacts:
              path: video-messenger/build/outputs
              destination: apk

      - store_artifacts:
              path: messenger/build/outputs
              destination: apk
